<a href="https://colab.research.google.com/github/nachiketjuneja/ml-cookbook/blob/main/code/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Linear Regression
## Dataset - house pricing dataset (Already available in the library)
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 63.9 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikit-learn-1.8.0

In [ ]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

In [ ]:
df = fetch_california_housing()
df

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [ ]:
df = fetch_california_housing()
pd.DataFrame(df.data)
## Output has 12 cols which means I have 12 features here

            0     1         2         3       4         5      6       7
0      8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1      8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2      7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3      5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4      3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
...       ...   ...       ...       ...     ...       ...    ...     ...
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

[20640 rows x 8 columns]

In [ ]:
## Check all the features and replace them in the columns.
## print df to view all available attributes. All these are independent features

dataset = pd.DataFrame(df.data)
dataset.columns = df.feature_names
dataset.head()

   MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [ ]:
## Since this is housing pricing dataset, we can predict the price which would be the dependent feature
dataset['price']=df.target
dataset.head(50)

    MedInc  HouseAge  AveRooms  AveBedrms  ...  AveOccup  Latitude  Longitude  price
0   8.3252      41.0  6.984127   1.023810  ...  2.555556     37.88    -122.23  4.526
1   8.3014      21.0  6.238137   0.971880  ...  2.109842     37.86    -122.22  3.585
2   7.2574      52.0  8.288136   1.073446  ...  2.802260     37.85    -122.24  3.521
3   5.6431      52.0  5.817352   1.073059  ...  2.547945     37.85    -122.25  3.413
4   3.8462      52.0  6.281853   1.081081  ...  2.181467     37.85    -122.25  3.422
5   4.0368      52.0  4.761658   1.103627  ...  2.139896     37.85    -122.25  2.697
6   3.6591      52.0  4.931907   0.951362  ...  2.128405     37.84    -122.25  2.992
7   3.1200      52.0  4.797527   1.061824  ...  1.788253     37.84    -122.25  2.414
8   2.0804      42.0  4.294118   1.117647  ...  2.026891     37.84    -122.26  2.267
9   3.6912      52.0  4.970588   0.990196  ...  2.172269     37.84    -122.25  2.611
10  3.2031      52.0  5.477612   1.079602  ...  2.263682     37.85    -122.26  2.815
11  3.2705      52.0  4.772480   1.024523  ...  2.049046     37.85    -122.26  2.418
12  3.0750      52.0  5.322650   1.012821  ...  2.346154     37.85    -122.26  2.135
13  2.6736      52.0  4.000000   1.097701  ...  1.982759     37.84    -122.26  1.913
14  1.9167      52.0  4.262903   1.009677  ...  1.954839     37.85    -122.26  1.592
15  2.1250      50.0  4.242424   1.071970  ...  2.640152     37.85    -122.26  1.400
16  2.7750      52.0  5.939577   1.048338  ...  2.395770     37.85    -122.27  1.525
17  2.1202      52.0  4.052805   0.966997  ...  2.138614     37.85    -122.27  1.555
18  1.9911      50.0  5.343675   1.085919  ...  2.362768     37.84    -122.26  1.587
19  2.6033      52.0  5.465455   1.083636  ...  2.509091     37.84    -122.27  1.629
20  1.3578      40.0  4.524096   1.108434  ...  2.463855     37.85    -122.27  1.475
21  1.7135      42.0  4.478142   1.002732  ...  2.538251     37.85    -122.27  1.598
22  1.7250      52.0  5.096234   1.131799  ...  2.123431     37.84    -122.27  1.139
23  2.1806      52.0  5.193846   1.036923  ...  2.624615     37.84    -122.27  0.997
24  2.6000      52.0  5.270142   1.035545  ...  2.383886     37.84    -122.27  1.326
25  2.4038      41.0  4.495798   1.033613  ...  2.663866     37.85    -122.28  1.075
26  2.4597      49.0  4.728033   1.020921  ...  2.539749     37.85    -122.28  0.938
27  1.8080      52.0  4.780856   1.060453  ...  2.775819     37.85    -122.28  1.055
28  1.6424      50.0  4.401691   1.040169  ...  2.391121     37.84    -122.28  1.089
29  1.6875      52.0  4.703226   1.032258  ...  2.548387     37.84    -122.28  1.320
30  1.9274      49.0  5.068783   1.182540  ...  2.283069     37.84    -122.28  1.223
31  1.9615      52.0  4.882086   1.090703  ...  2.648526     37.84    -122.28  1.152
32  1.7969      48.0  5.737313   1.220896  ...  3.062687     37.84    -122.27  1.104
33  1.3750      49.0  5.030395   1.112462  ...  2.291793     37.83    -122.27  1.049
34  2.7303      51.0  4.972015   1.070896  ...  2.347015     37.83    -122.27  1.097
35  1.4861      49.0  4.602273   1.068182  ...  2.159091     37.83    -122.27  0.972
36  1.0972      48.0  4.807487   1.155080  ...  2.639037     37.83    -122.27  1.045
37  1.4103      52.0  3.749380   0.967742  ...  2.235732     37.83    -122.28  1.039
38  3.4800      52.0  4.757282   1.067961  ...  2.229773     37.83    -122.26  1.914
39  2.5898      52.0  3.494253   1.027299  ...  1.978448     37.83    -122.26  1.760
40  2.0978      52.0  4.215190   1.060759  ...  2.394937     37.83    -122.26  1.554
41  1.2852      51.0  3.759036   1.248996  ...  2.076305     37.83    -122.26  1.500
42  1.0250      49.0  3.772487   1.068783  ...  2.444444     37.84    -122.26  1.188
43  3.9643      52.0  4.797980   1.020202  ...  2.358586     37.84    -122.26  1.888
44  3.0125      52.0  4.941781   1.065068  ...  2.260274     37.83    -122.26  1.844
45  2.6768      52.0  4.335079   1.099476  ...  1.879581     37.83    -122.26  1.823
46  2.0260      50.0  3.700658   1.059211  ...  2.026316     37.83    -122.26  1.425
47  1.7348      43.0  3.980237   1.233202  ...  2.205534     37.82    -122.27  1.375
48  0.9506      40.0  3.900000   1.218750  ...  2.643750     37.82    -122.26  1.875
49  1.7750      40.0  2.687500   1.065341  ...  1.988636     37.82    -122.27  1.125

[50 rows x 9 columns]

In [ ]:
## Divide dataset to independent and dependent features
## use iloc to provide features which are dependent/independent

x=dataset.iloc[:,:-1] ## all cols except last one. independent features
y=dataset.iloc[:,-1] ## only last col. dependent feature
x.head()
y.head()

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: price, dtype: float64